#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP

print_domain () {
	result=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:'| grep "$2");
	echo "$2 $result" | awk '{print "The subdomain "$1" is a "$5" record and points to "$6""}'
}

if [ "$#" == "1" ]
then
	print_domain "$1" "www"
	print_domain "$1" "lb-01"
	print_domain "$1" "web-01"
	print_domain "$1" "web-02"

else
	print_domain "$1" "$2"
fi
