#!/usr/bin/env bash
#Install nginx on
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i "47i\\\tlocation /redirect_me {\n\t\t return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n" /etc/nginx/sites-available/default
echo -e "Ceci n'est pas une page\n" > /usr/share/nginx/html/error_404.html
sed -i "50i \\\terror_page 404 /error_404.html;\n\tlocation = /error_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n" /etc/nginx/sites-available/default
sed -i "56i \\\tadd_header X-Server-By $hostname;\n" /etc/nginx/sites-available/default
service nginx restart
