#!/usr/bin/env bash
# It displays the content of the file /etc/passwd

FILENAME="/etc/passwd"
OLDIFS=$IFS
IFS=:
 
while read -r  USERNAME PASSWORD USER_ID GROUP_ID COMMENT HOME_DIRECTORY LOGINSHELL
do
  echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $LOGINSHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID"
done < $FILENAME
 
IFS=$OLDIFS
