#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
h=0
while ((i <= 720))
do
    if ((i % 60 == 0)) || ((i == 0))
    then
      echo Hour: "$h"
      h=$(( h + 1 ))
    else
      echo "$i"
    fi
i=$(( i + 1 ))
done
