#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
h=0
while ((h <= 13))
do
    if ((i == 0))
    then
      echo Hour: "$h"
      h=$(( h + 1 ))
      i=$(( i + 1 ))
    elif ((i % 60 == 0))
      then
      if ((h != 13))
      then
        echo Hour: "$h"
      fi
      h=$(( h + 1 ))
      i=1
    else
      echo "$i"
      i=$(( i + 1 ))
    fi
done
