#!/usr/bin/env bash
#Insall uwf and configure to open ports for 22, 443, 80

apt-get -y update
apt-get -y install ufw
ufw default deny incoming
ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp
ufw enable
