#!/usr/bin/env bash
#Insall uwf and configure to open ports for 22, 443, 80
sudo apt -y update
sudo apt -y install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
