#!/usr/bin/env bash
# It configures an Ubuntu server with the below requirements.
sed s/^127.0.0.1/127.0.0.2/ /etc/hosts | sed s/^157.240.21.35/8.8.8.8/  > /etc/hosts.new
sudo rm -rf /etc/hosts
sudo cp /etc/hosts.new /etc/hosts
