#!/usr/bin/env bash
# It configures an Ubuntu server with the below requirements.
sed s/^127.0.0.1/127.0.0.2/ /etc/hosts > /etc/hosts.new
echo "8.8.8.8 facebook.com" >> /etc/hosts.new
sudo rm -rf /etc/hosts
sudo cp /etc/hosts.new /etc/hosts
