#!/usr/bin/env bash
#run nginx as user nginx
user=$(grep user /etc/nginx/nginx.conf | awk '{print $2}')
sed -i "s/$user/nginx;/g" /etc/nginx/nginx.conf
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
